name: Pages

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   
    - name: Install Node
      uses: actions/setup-node@v1
      with:
          node-version: 16.4.0

    - name: npm dependencies
      run: npm install
    
    - name: npm progess
      run: npm set progress=false && npm config set depth 0 && npm cache clean --force
    
    - name: npm ng-app
      run: npm i && mkdir ./ng-app && cp -R ./node_modules ./ng-app

    - name: npm sass
      run: npm rebuild node-sass --force

    - name: Deploy
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
