name: Pages

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   
    - name: Install Node
      uses: actions/setup-node@v1
      with:
          node-version: 16.4.0

    
    # - name: npm progess
    #   run: npm set progress=false && npm config set depth 0 && npm cache clean --force
    
    - name: npm ng-app
      run: npm i angular@1.7.2 &&  $(npm bin)/ng -v
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



    # - name: Deploy
    #   run: cp ./* /ng-app; cd /ng-app && $(npm bin)/ng build
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
