name: Pages

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   
    - name: Install Node
      uses: actions/setup-node@v1
      with:
          node-version: 16.4.0

    
    # - name: npm progess
    #   run: npm set progress=false && npm config set depth 0 && npm cache clean --force
    
    - name: npm ng-app
      run: rm $(npm bin)/ng; npm i;$(npm bin)/ng build; rm -rf ./docs; mkdir -p ./docs; echo "resumex.downloadpdf.org" > ./docs/CNAME;mv ./dist/* ./docs; 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: npm push
      run: git config --global user.email "nathan.d.armstrong@gmail.com";  git config --global user.name "stashedup"; git add .; git commit -m "test";git push 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        



    # - name: Deploy
    #   run: cp ./* /ng-app; cd /ng-app && $(npm bin)/ng build
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
